// LOGICAL STATEMENTS;
//  USING AND (&&) OPERATOR; 
var A = 12;
var B = 12;
console.log(A == 12 && B == 12); // Output: true;
// USING OR(||) OPERATOR;
var num1 = 15;
var num2 = 18;
console.log(num1 == 15 || num2 == num1); // Output: true;
// USING NOT (!) OPERATOR;
var FIRSTNAME = "ali";
var SECONDNAME = "ali";
console.log(!(FIRSTNAME == SECONDNAME)); // Output: false;
